### ISSUE TITLE
M05-Unit 6 Create a front door for a highly available web application using the Azure portal.md -- Missing/broken graphics

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#1]
# Module: 05
#### Step: 00

Description of issue

While the very first graphic displays OK, all of the subsequent references to graphics in the Media dir are broken.

For example:

![image](https://user-images.githubusercontent.com/49700217/177641789-afbff336-dfeb-43c2-a07e-45a40fe2a659.png)

These point to the following paths, but no .png files of those names exist in the Media dir:
(../media/search-front-door.png)

(../media/add-frontends-domains.png)

(../media/add-backends.png)

(../media/add-routing-rules.png)

(../media/frontend-url.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Now, the https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr/blob/OLPRODLOC/Instructions/Exercises/M05-Unit%206%20Create%20a%20front%20door%20for%20a%20highly%20available%20web%20application%20using%20the%20Azure%20portal.md show images. Fixed.
