### ISSUE TITLE
M07-단원 5 가상 네트워크 서비스 엔드포인트로 PaaS 리소스에 대한 네트워크 액세스 제한 -Typos Reported

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#10]
# Module: 07

Description of issue

Typos were reported:

Task 1/Step 5
typo : "공용" --> "public"

Task 2/Step 3
typo : "프라이빛" --> "private"

**Comment by chriscarty00** [comment]
[Locfile ](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtXV0xfTEFCLUFaLTcwMC5tYXN0ZXI8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7S29yZWFuIChLb3JlYSk8L1FSPjxRUiBJZD0iNSIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtFcXVhbDtNMDctVW5pdCA2IENyZWF0ZSBhbiBBenVyZSBwcml2YXRlIGVuZHBvaW50IHVzaW5nIEF6dXJlIFBvd2VyU2hlbGwubWQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d)to update
