### ISSUE TITLE
M08-단원 3 Azure Monitor를 사용하여 부하 분산 장치 리소스 모니터링 - Typo reported

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#11]
# Module: 08
#### Step: 03&4

Description of issue

Typo was reported in Task 7, Steps 3&4:
typo : 
"연결 대상 상자에서 가상 머신 을 선택합니다."
---->
"IP 구성 + 추가"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtXV0xfTEFCLUFaLTcwMC5tYXN0ZXI8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7S29yZWFuIChLb3JlYSk8L1FSPjxRUiBJZD0iNCIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtFcXVhbDtNMDgtVW5pdCAzIE1vbml0b3IgYSBsb2FkIGJhbGFuY2VyIHJlc291cmNlIHVzaW5nIEF6dXJlIE1vbml0b3IubWQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d) for update

**Comment by chriscarty00** [comment]
Fixed and uploaded
