### ISSUE TITLE
M03-Unit 5 Provision an ExpressRoute circuit.md: ENG version updates being translated soon?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#2]
This set of instructions has had an update in the ENG version, hopefully it will soon be translated and updated here?  Note that with this change it is important to have an updated screenshot showing the new settings.  I am including a reference to the ENG version highlighting the important changes:

![image](https://user-images.githubusercontent.com/49700217/203122721-8e1a220b-1d06-4b20-a85b-0ed88de5b052.png)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfiles](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEFzc2V0IElEO0VxdWFsO2V4cHJlc3Nyb3V0ZS1jcmVhdGUtY29uZmlndXJhdGlvbjIucG5nPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d) may need bugfix HO

**Comment by chriscarty00** [comment]
The file was missing from the OLProdLoc and main branch - added it to both manually 
The Locfile is an art file and following discussion with the PM this will remain in English
