### ISSUE TITLE
M05-단원 4 Azure Application Gateway 배포 - Typos Reported

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#5]
# Module: 05
#### Step: 18 & 21

Description of issue

Several typos were reported in 'M05-단원 4 Azure Application Gateway 배포'

Task 1/Step 18:

typo : 
"수신기 이름 : 수신기" --> "수신기 이름 : listener"

typo : 
"프런트 엔드 IP : Public 을 선택합니다."
-- "프런트 엔드 IP : 공용 을 선택합니다."

Task 1/Step 21:

typo : 
"대상 형식 : 백 엔드 풀" --> "대상 형식 : BackEndPool"
"HTTP 설정 : 새로 추가" --> "백엔드 설정 : 새로 추가"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7TTA1LVVuaXQgNCBEZXBsb3kgQXp1cmUgYXBwbGljYXRpb24gZ2F0ZXdheS5tZDwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) to update

Pages has been rewritten so only one option remains to be updated

**Comment by chriscarty00** [comment]
Fixed and uploaded
