### ISSUE TITLE
M06-단원 7 Azure Portal을 사용하여 Azure Firewall 배포 및 구성- Multiple Typos

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#7]
# Module: 06
#### Step: multiple

Description of issue

Several typos were reported in 'M06-단원 7 Azure Portal을 사용하여 Azure Firewall 배포 및 구성'

Task 1/Step 5
typo : "지역을" --> "미국 동부"

Task 4/Step 3
typo : "지역" --> "미국 동부"

Task 5/Step 3
typo : "지역" --> "미국 동부"

Task 5/Step 13
typo :
주소 접두사 에 0.0.0.0/0 을 입력합니다
-->
주소 접두사 대상 : IP 주소
대상 IP 주소 / CIDR 범위 : 0.0.0.0/0

Task 6/Step 5:
"typo : ""규칙섹션""
속성 --> 이름
소스형식 --> 원본유형"

Task 7/Step 3:
typo : ""규칙섹션""
속성 --> 이름
소스형식 --> 원본유형

Task 8/Step 3:
typo : "규칙섹션"
속성 --> 이름
소스형식 --> 원본유형

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
[Locfile](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPlRydWU8L1NBVE8%2bPFNBTE8%2bRmFsc2U8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQ29udGVudCBHcm91cDtFcXVhbDtXV0xfTEFCLUFaLTcwMC5tYXN0ZXI8L1FSPjxRUiBJZD0iMyIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7S29yZWFuIChLb3JlYSk8L1FSPjxRUiBJZD0iOCIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7RmlsZXM7SG9zdCBBc3NldCBJRDtFcXVhbDtNMDYtVW5pdCA0IENvbmZpZ3VyZSBERG9TIFByb3RlY3Rpb24gb24gYSB2aXJ0dWFsIG5ldHdvcmsgdXNpbmcgdGhlIEF6dXJlIHBvcnRhbC5tZDwvUVI%2bPC9RVD48Ukc%2bPEdDPk5VTEw8L0dDPjwvUkc%2bPC9WUFE%2b) to update

**Comment by chriscarty00** [comment]
Some text had changed fixed where possible
