### ISSUE TITLE
M06-단원 9 Azure Firewall Manager를 사용하여 가상 허브 보호 - Typos reported

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions.ko-kr#8]
# Module: 06
#### Step: multiple

Description of issue
Several typos were reported in M06-단원 9 Azure Firewall Manager를 사용하여 가상 허브 보호

Task 1/Step 5:
typo : "지역" --> "미국 동부"

Task 2/Step 6:
typo : "지역" --> "미국 동부"

Task 5/Step 6:
typo : "지역" --> "미국 동부"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
No Task 2/Step 6  now
Task 5/Step 6 rewritten 
Other fix taken
